version: "3"

services:
  app:
    build: .
    command: npm run dev
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/home/node/app"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:${PG_PORT}"